[package]
name = "dashmap"
version = "4.0.2"
authors = ["Acrimon <joel.wejdenstal@gmail.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/xacrimon/dashmap"
homepage = "https://github.com/xacrimon/dashmap"
description = "Blazing fast concurrent HashMap for Rust."
readme = "README.md"
documentation = "https://docs.rs/dashmap"
keywords = ["atomic", "concurrent", "hashmap"]
categories = ["concurrency", "algorithms", "data-structures"]

[features]
default = []
raw-api = []

[dependencies]
num_cpus = "1.13.0"
serde = { version = "1.0.118", optional = true, features = ["derive"] }
cfg-if = "1.0.0"
rayon = { git = "https://github.com/ryoqun/rayon", rev = "443200afa00c590a8324f3f31bc3c92f8f220b50", optional = true }

[package.metadata.docs.rs]
features = ["rayon", "raw-api", "serde"]
